### ISSUE TITLE
TLS Connection Issue After Updating to v7.0.0

### ISSUE THREAD

**Issue by neverovski** [pinojs/pino-elasticsearch#180]
When updating from 6.7.0 to 7.0.0 the connection is failing. I didn't change the connection settings.

I can look into this issue further and send a **PR**

My settings:
```ts
pinoElasticsearch({
    index: 'log',
    node: 'https://127.0.0.1:9200',
    esVersion: 8,
    auth: { apiKey: 'LOG_API_KEY' },
    tls: {
        ca: 'LOG_SSL_CA',
        rejectUnauthorized: true,
    },
    opType: 'create'
})
```

Error messages:
```text
'Elasticsearch client error': ConnectionError: unable to verify the first certificate
      at SniffingTransport.request (/node_modules/@elastic/transport/src/Transport.ts:585:17)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at Client.BulkApi [as bulk] (//node_modules/@elastic/elasticsearch/src/api/api/bulk.ts:75:10) {
    meta: {
      body: undefined,
      statusCode: 0,
      headers: {},
      meta: {
        context: null,
        request: {
          params: {
            method: 'POST',
            path: '/_bulk',
            body: '{"index":{"_index":"logs-11-04","op_type":"create"}}\n' +
```

My environment:
- pino-elasticsearch: v7.0.0
- nodejs: v18.17.0
- npm: v9.6.7

**Comment by mcollina** [comment]
Thanks, a PR would be amazing.

**Comment by CptSchnitz** [comment]
Hi, i wouldn't mind taking care of this issue.

**Comment by neverovski** [comment]
I send PR https://github.com/pinojs/pino-elasticsearch/pull/181

**Comment by neverovski** [comment]
In Elasticsearch 8, the parameter for configuring secure communication has been updated to 'TLS' instead of 'SSL'. This commit adjusts the code to reflect this change, ensuring compatibility with Elasticsearch 8.

**Comment by CptSchnitz** [comment]
I don't think it depends on ES cluster version. It's `elasticsearch-js` package breaking their API in v8.0.0.
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/changelog-client.html#_rename_ssl_option_to_tls

**Comment by neverovski** [comment]
> I don't think it depends on ES cluster version. It's `elasticsearch-js` package breaking their API in v8.0.0. https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/changelog-client.html#_rename_ssl_option_to_tls

That's right, in version 8 they changed the ssl option to tls
